# Simple MkDocs Configuration for AuthentiCred
site_name: AuthentiCred Documentation
site_description: Blockchain-based credential verification platform
site_author: richarddushime

# GitHub Pages configuration
site_url: https://richarddushime.github.io/AuthentiCred/
repo_url: https://github.com/richarddushime/AuthentiCred
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

# Navigation
nav:
  - Home: index.md
  - Technical Documentation: authenticred_technical_documentation.md
  - Technology Stack: authenticred_technology_stack.md
  - Management Commands: authenticred_management_commands.md
  - Contributing Guide: authenticred_contributing_guide.md
  - Automation Setup: authenticred_automation_setup.md
  - Tailwind Setup: authenticred_tailwind_setup.md
  - API Reference: api/index.md

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes

  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde

# Plugins
plugins:
  - search
