[phases.setup]
nixPkgs = ["python311", "nodejs_18", "npm"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cd theme && npm install && npm run build-prod && cd .."
]

[start]
cmd = "gunicorn AuthentiCred.wsgi:application -c gunicorn.conf.py"

[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "18"
