[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "chmod +x start.sh && ./start.sh"

[deploy.healthcheck]
path = "/"
interval = "60s"
timeout = "30s"
retries = 5

[deploy.variables]
PYTHON_VERSION = "3.11.0"
NODE_VERSION = "18.0.0"
RAILWAY = "true"
