# Generated by Django 5.2.3 on 2025-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIDRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnChainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_type', models.CharField(choices=[('DID_REGISTRATION', 'DID Registration'), ('CREDENTIAL_ANCHORING', 'Credential Anchoring'), ('CREDENTIAL_REVOCATION', 'Credential Revocation'), ('TRUST_UPDATE', 'Trust Status Update')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
