# Generated by Django 5.2.3 on 2025-07-13 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='didregistration',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='did_registrations', to='blockchain.onchaintransaction'),
        ),
        migrations.AddField(
            model_name='didregistration',
            name='trust_updated',
            field=models.BooleanField(default=False),
        ),
    ]
