# Generated by Django 5.2.3 on 2025-07-12 21:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vc_json', models.JSONField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('credential_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('type', models.CharField(choices=[('DEGREE', 'Academic Degree'), ('CERTIFICATE', 'Professional Certificate'), ('BADGE', 'Digital Badge'), ('TRANSCRIPT', 'Academic Transcript'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('fields', models.JSONField(help_text='JSON structure defining the credential fields')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
