# Generated by Django 5.2.5 on 2025-08-26 19:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_hash', models.CharField(help_text='64-character hex hash of the credential', max_length=64)),
                ('verification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=False)),
                ('verification_details', models.JSONField(default=dict, help_text='Detailed verification results')),
                ('source', models.CharField(choices=[('INTERNAL', 'Internal Database'), ('EXTERNAL', 'External Credential')], default='INTERNAL', max_length=20)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='credentials.credential')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verification_date'],
                'indexes': [models.Index(fields=['verifier', '-verification_date'], name='credentials_verifie_63cdee_idx'), models.Index(fields=['credential_hash'], name='credentials_credent_f85a63_idx')],
            },
        ),
    ]
