# Generated by Django 5.2.5 on 2025-08-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_verificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='vc_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the credential JSON', max_length=64, null=True, unique=True),
        ),
    ]
