# Generated by Django 5.2.5 on 2025-08-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_populate_vc_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF, JPG, PNG, or other document formats', null=True, upload_to='credentials/'),
        ),
    ]
