# name: Deploy to Heroku

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.13'
    
#     - name: Install Heroku CLI
#       run: |
#         curl https://cli-assets.heroku.com/install.sh | sh
#         heroku --version
    
#     - name: Install Python dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
    
#     - name: Run tests before deployment
#       env:
#         SECRET_KEY: ${{ secrets.SECRET_KEY }}
#         DEBUG: False
#         HEROKU: true
#         DJANGO_SETTINGS_MODULE: AuthentiCred.settings
#       run: |
#         python manage.py check --deploy
    
#     - name: Deploy to Heroku
#       env:
#         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#         AUTHENTICRED: ${{ secrets.AuthentiCred }}
#       run: |
#         echo "Deploying to Heroku app: $AUTHENTICRED"
#         heroku container:login
#         heroku container:push web --app $AUTHENTICRED
#         heroku container:release web --app $AUTHENTICRED
        
#         echo "Deployment completed successfully!"
#         echo "Your app is available at: https://$AUTHENTICRED.herokuapp.com/"
